<?php echo $this->headScript()->appendFile('./js/gseguros.operaciones.cuenta-corriente.cc-compania.js');?>

<b>Cliente:</b> <?=$this->compania?>
<table>
  <tr>
    <th>Moneda</th>
    <th>Polizas Pago</th>
    <th>Polizas Debe</th>
    <!--  th>Movimientos</th>-->
    <th>Saldo</th>
  </tr>
  <tr>
    <td>Pesos</td>
    <td><?=(empty($this->pago_pesos))?'0':$this->pago_pesos?></td>
    <td><?=(empty($this->debe_pesos))?'0':$this->debe_pesos?></td>
   <?php // <td>=(empty($this->suma_movimientos_pesos))?'0':$this->suma_movimientos_pesos</td> ?>
    <td><?= ( ($this->debe_pesos+$this->pago_pesos) - $this->suma_movimientos_pesos )?></td>
  </tr>
  <tr>
    <td>Dolar</td>
    <td><?=(empty($this->pago_dolar))?'0':$this->pago_dolar?></td>
    <td><?=(empty($this->debe_dolar))?'0':$this->debe_dolar?></td>
   <?php //  <td>=(empty($this->suma_movimientos_dolar))?'0':$this->suma_movimientos_dolar</td> ?>
    <td><?= ( ($this->debe_dolar+$this->pago_dolar) - $this->suma_movimientos_dolar )?></td>
  </tr>
  <tr>
    <td>Euro</td>
    <td><?=(empty($this->pago_euro))?'0':$this->pago_euro?></td>
    <td><?=(empty($this->debe_euro))?'0':$this->debe_euro?></td>
    <?php //<td><?=(empty($this->suma_movimientos_euro))?'0':$this->suma_movimientos_euro</td> ?>
    <td><?= (($this->debe_euro+$this->pago_euro) - $this->suma_movimientos_euro )?></td>
  </tr>
</table>

<form id="busqueda_poliza_movimientos_form" onSubmit="return false"> 
<table>
 <tr><td>Nro: P&oacute;liza</td>
  <input type="hidden" name="buscar_poliza" value=1></input>
  <td><input name="busqueda_compania" id="id_compania_movimientos" type="hidden" value=<?=$this->compania_id?> ></input></td>
  <td><input type="text" name="numero_poliza" id="numero_poliza" value=""></input></td>
  <td><input id="busqueda_poliza_movimientos" type="button" value="Buscar"></input></td>
</tr>
</table>
</form>

<table class="ui-widget" >
	<thead class="ui-widget-header">
	<tr>
		<th>Nro. Movimiento</th>	
		<th>Fecha</th>
		<th>Moneda</th>
		<th>Importe</th>
    <th>Descuento</th>
    <th colspan="3">Datos Cheque</th>
		<th></th>
	</tr>
</thead>
<tbody class="ui-widget-content">

<?
foreach ($this->rows as $row):
$moneda = Domain_Helper::getHelperNameById('moneda', $row['moneda_id']);
$datos_cheques = Domain_Movimiento::getDatosCheques($row['movimiento_id']);
?>

	<tr>
		<td rowspan="4"><?=$row['movimiento_id']?></td>
		<td rowspan="4"><?=$row['fecha_pago']?></td>
		<td rowspan="4"><?=$moneda?></td>
		<td rowspan="4"><?=round($row['importe'],2)?></td>
		<td rowspan="4"><?=$row['descuento']?></td>
    <td class="ui-widget-header">Banco</td>
    <td class="ui-widget-header">Numero</td>
    <td class="ui-widget-header">Importe</td>
		<td rowspan="4"><input type="button" value="Ver Detalle" onClick="return viewDetalleMovimientoCompania('./operaciones/cuenta-corriente/detalle-movimiento-compania/movimiento_id/<?=$row['movimiento_id']?>')"> </input> </td>
	</tr>
 <tr>
    <td><?=$datos_cheques[0]['banco']?></td>
    <td><?=$datos_cheques[0]['numero']?></td>
    <td><?=$datos_cheques[0]['importe']?></td>
 </tr>
  <tr>
     <td><?=$datos_cheques[1]['banco']?></td>
    <td><?=$datos_cheques[1]['numero']?></td>
    <td><?=$datos_cheques[1]['importe']?></td>
 </tr>
   <tr>
     <td><?=$datos_cheques[2]['banco']?></td>
    <td><?=$datos_cheques[2]['numero']?></td>
    <td><?=$datos_cheques[2]['importe']?></td>
 </tr>
	<?endforeach;?>
</tbody>
</table>
<input id="atras_cuenta_corriente" type="button" value="Atras" onClick="return onClickAtras('./operaciones/cuenta-corriente/list-compania')"></input>
</form>
</div>
<?= $this->paginationControl($this->rows, 'Sliding', 'paginator.phtml',array('compania_id'=>$this->compania_id)); ?>