<? $date_hoy = new DateTime();
	$fecha_hoy =  $date_hoy->format('d/m/Y');?>

<h3>P&oacute;lizas a Vencer al <?=$fecha_hoy?></h3>

<table id="poliza_vencimientos" class="ui-widget" cellspacing="1" cellpadding="0" border="0" >

	<thead  class="ui-widget-header" >
		<tr>
			<th>Vencimiento</th>	
			<th>Tomador</th>
			<th>Numero P&oacute;liza</th>
			<th>Endoso</th>
			<th>Tipo de Cobertura</th>
			<th>Compa&ntilde;ia</th>
			<th></th>
 		</tr>
	</thead>
	<tbody   class="ui-widget-content" >
	<?foreach ($this->rows as $poliza):?>
	<? //Esto lo puedo hacer con metodos estaticos
	$d_poliza = new Domain_Poliza($poliza['poliza_id']);
	$m_poliza_valores = $d_poliza->getModelPolizaValores();

	$asegurado = new Domain_Asegurado($poliza['asegurado_id']);
	$m_asegurado = $asegurado->getModel();
	$compania = new Domain_Compania($poliza['compania_id']);
	$m_compania = $compania->getModel();
	$estado = Domain_EstadoPoliza::getNameById($poliza['estado_id']);
	$estado_codigo = Domain_EstadoPoliza::getCodigoById($poliza['estado_id']);
	$tipo_poliza = Domain_TipoPoliza::getNameById($poliza['tipo_poliza_id']);
	$cantidad_cuotas = (float) Domain_DetallePago::getCantidadCuotas($d_poliza->getModelDetallePago()->detalle_pago_id);
	$valor_cuotas = (float) Domain_DetallePago::getValorCuotas($d_poliza->getModelDetallePago()->detalle_pago_id);
	$importe = $cantidad_cuotas * $valor_cuotas;

	//echo 'este tipo:'.$tipo_poliza.' este importe '.$importe;
	$operacion = Domain_Helper::getHelperNameById('operacion', $poliza['operacion_id']);

	$m_detalle_poliza = $d_poliza->getModelDetalle();
	//Aca podria traer el objeto correspondiente en vez de instanciarlo por separado
	
	switch ($tipo_poliza) {
		case 'AUTOMOTORES':

			$tipo_cobertura = Domain_Helper::getHelperNameById('tipo_cobertura_automotores', $m_detalle_poliza->tipo_cobertura_id);
			break;

		case 'ADUANEROS':

			$tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
			
			break;
			
		case 'ACCIDENTES_PERSONALES':

			$tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
			break;
			
		case 'CONSTRUCCION':

			$tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
			break;
		case 'SEGURO_TECNICO':

			$tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
			break;
		case 'ALQUILER':

			$tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id, $poliza['tipo_poliza_id']);
			break;
		case 'TRANSPORTE_MERCADERIA':
                        $tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
                        
               break;
        case 'RESPONSABILIDAD_CIVIL':
                        $tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
                        
               break;       
		 case 'IGJ':
                        $tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
                        
               break;       
		case 'JUDICIALES':
                        $tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
                        
               break;
        case 'INTEGRAL_COMERCIO':
                        $tipo_cobertura = Domain_MotivoGarantia::getMotivoGarantiaByIdAndTipoPoliza($m_detalle_poliza->motivo_garantia_id,$poliza['tipo_poliza_id']);
                        
               break;               
			
		default:
			$tipo_cobertura = null;
			break;

	}


	?>
		<tr>
			<td><?=$this->traduceFecha($poliza['fecha_vigencia_hasta'])?></td>	
			<td><?=$m_asegurado->nombre ?></td>
			<td><?=$poliza['numero_poliza']?></td>
			<td><?=$poliza['endoso']?></td>
			<td><?=$tipo_cobertura?></td>
			<td><?=$m_compania->nombre ?></td>
		</tr>

		<?endforeach; ?>
	</tbody>
</table>